
project_id = "hytudwviatqbtwnlqsdl"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost.test"]
jwt_expiry = 3600
enable_signup = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions]
enabled = true

[functions.flutterwave-webhook]
verify_jwt = false
